'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import styles from './landing.module.css';

interface QueueItem {
  id: string;
  type: string;
  status: 'Pending' | 'Synced';
}

interface AuditLog {
  action: string;
  value: string;
  time: string;
}

export default function LandingPage() {
  // --- Card 1: Logger States ---
  const [sampleType, setSampleType] = useState('Blood');
  const [source, setSource] = useState('Patient');
  const [logCount, setLogCount] = useState(41);
  const [isLogging, setIsLogging] = useState(false);
  const [logFeedback, setLogFeedback] = useState<string | null>(null);

  const getPrefix = (type: string) => {
    return type.slice(0, 3).toUpperCase();
  };

  const generatedId = `${getPrefix(sampleType)}-${String(logCount + 1).padStart(3, '0')}`;

  const handleQuickLog = (e: React.FormEvent) => {
    e.preventDefault();
    if (isLogging) return;
    setIsLogging(true);
    setLogFeedback(null);

    setTimeout(() => {
      setLogCount(prev => prev + 1);
      setIsLogging(false);
      setLogFeedback(`Saved: ${generatedId}`);
      setTimeout(() => setLogFeedback(null), 2500);
    }, 800);
  };

  // --- Card 2: Offline Sync States ---
  const [isOnline, setIsOnline] = useState(false);
  const [syncQueue, setSyncQueue] = useState<QueueItem[]>([
    { id: 'local-203', type: 'DNA', status: 'Pending' },
    { id: 'local-204', type: 'Saliva', status: 'Pending' }
  ]);
  const [isSyncing, setIsSyncing] = useState(false);

  const addOfflineSample = () => {
    const types = ['Blood', 'DNA', 'Saliva'];
    const randomType = types[Math.floor(Math.random() * types.length)];
    const newLocalId = `local-${Math.floor(Math.random() * 900) + 100}`;
    setSyncQueue(prev => [...prev, { id: newLocalId, type: randomType, status: 'Pending' }]);
  };

  // Run auto-sync effect when toggled to online
  useEffect(() => {
    if (isOnline && syncQueue.some(item => item.status === 'Pending') && !isSyncing) {
      setIsSyncing(true);
      
      let currentQueue = [...syncQueue];
      let delay = 600;

      currentQueue.forEach((item, index) => {
        if (item.status === 'Pending') {
          setTimeout(() => {
            setSyncQueue(prev => 
              prev.map(q => q.id === item.id ? { ...q, status: 'Synced' } : q)
            );
            if (index === currentQueue.length - 1 || !currentQueue.slice(index + 1).some(q => q.status === 'Pending')) {
              setIsSyncing(false);
            }
          }, delay);
          delay += 600;
        }
      });
    }
  }, [isOnline, syncQueue, isSyncing]);

  // --- Card 3: Audit Trail States ---
  const [phase, setPhase] = useState<'Collection' | 'Extraction' | 'Amplification' | 'Analysis'>('Collection');
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([
    { action: 'CREATE', value: 'Specimen generated by Student A', time: '10:14:02' }
  ]);

  const advancePhase = () => {
    const phases: Array<'Collection' | 'Extraction' | 'Amplification' | 'Analysis'> = [
      'Collection', 'Extraction', 'Amplification', 'Analysis'
    ];
    const currentIndex = phases.indexOf(phase);
    const nextIndex = (currentIndex + 1) % phases.length;
    const nextPhase = phases[nextIndex];
    setPhase(nextPhase);

    const timeStr = new Date().toTimeString().split(' ')[0];
    const newLog = {
      action: 'PHASE_CHANGE',
      value: `Phase updated to ${nextPhase} by Admin`,
      time: timeStr
    };
    setAuditLogs(prev => [newLog, ...prev]);
  };

  // --- Intersection Observer for Scroll reveal animations ---
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add(styles.active);
            observer.unobserve(entry.target);
          }
        });
      },
      {
        threshold: 0.05,
        rootMargin: '0px 0px -50px 0px',
      }
    );

    const elements = document.querySelectorAll(`.${styles.reveal}`);
    elements.forEach((el) => observer.observe(el));

    return () => {
      elements.forEach((el) => observer.unobserve(el));
    };
  }, []);

  return (
    <div className={styles.page}>
      {/* Header */}
      <header className={styles.header}>
        <div className={styles.headerInner}>
          <span className={styles.logo}>
            <svg className={styles.logoIcon} viewBox="0 0 24 24">
              <path d="M4.5 16.5c-1.5 1.25-2.5 3-2.5 5.5h20c0-2.5-1-4.25-2.5-5.5" />
              <path d="M12 2C7.5 2 6 5.5 6 9c0 3.5 1.5 7.5 6 7.5s6-4 6-7.5c0-3.5-1.5-7-6-7z" />
            </svg>
            LabFlow
          </span>

        </div>
      </header>

      <main className={styles.main}>
        {/* Hero Section */}
        <section className={styles.heroSection}>
          <div className={styles.heroContent}>

            <h1 className={`${styles.heroTitle} ${styles.reveal} ${styles.stagger2}`}>
              Never lose track of a sample again.
            </h1>
            <p className={`${styles.heroSubtitle} ${styles.reveal} ${styles.stagger3}`}>
              Log samples in seconds. Track everything. Even offline.
            </p>
            <div className={`${styles.heroActions} ${styles.reveal} ${styles.stagger3}`}>
              <Link href="/auth?mode=signup" prefetch={false} className={styles.ctaPrimary}>
                Register Lab
              </Link>
            </div>
          </div>
        </section>

        {/* Feature Section */}
        <section className={styles.featureSection}>
          <div className={`${styles.sectionHeader} ${styles.reveal}`}>
            <h2 className={styles.sectionTitle}>Built for High-Friction Environments</h2>
            <p className={styles.sectionSubtitle}>
              Engineered with physical lab realities in mind. Test our key core interactions right below.
            </p>
          </div>

          <div className={styles.featureGrid}>
            {/* Card 1: One-Handed Logger */}
            <div className={`${styles.card} ${styles.reveal} ${styles.stagger1}`}>
              <div className={styles.cardHeader}>
                <div className={styles.cardIcon}>
                  <svg viewBox="0 0 24 24">
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                    <path d="M18.5 2.5a2.121 2.121 0 1 1 3 3L12 15l-4 1 1-4z" />
                  </svg>
                </div>
                <h3 className={styles.cardTitle}>One-Handed Wet Lab Logger</h3>
                <p className={styles.cardDesc}>
                  Built for real lab conditions. Minimal input, easy to use mid-experiment, with instant sample ID generation.
                </p>
              </div>

              <div className={styles.cardInteractive}>
                <form onSubmit={handleQuickLog} className={styles.loggerForm}>
                  <div>
                    <label style={{ display: 'block', fontSize: 10, marginBottom: 4, fontWeight: 600 }}>Specimen Type</label>
                    <select value={sampleType} onChange={e => setSampleType(e.target.value)} className={styles.loggerSelect}>
                      <option value="Blood">Blood (BLD)</option>
                      <option value="Tissue">Tissue (TIS)</option>
                      <option value="DNA">DNA Extract (DNA)</option>
                      <option value="Saliva">Saliva (SAL)</option>
                    </select>
                  </div>
                  <div>
                    <label style={{ display: 'block', fontSize: 10, marginBottom: 4, fontWeight: 600 }}>Sample Source</label>
                    <input type="text" value={source} onChange={e => setSource(e.target.value)} className={styles.loggerInput} placeholder="e.g. Patient ID, Control" />
                  </div>
                  <div className={styles.loggerPreview}>
                    <span className={styles.loggerIdLabel}>Allocated display ID:</span>
                    <span className={styles.loggerBadge}>{generatedId}</span>
                  </div>
                  <button type="submit" disabled={isLogging} className={styles.loggerBtn}>
                    {isLogging ? 'Saving Record...' : logFeedback ? logFeedback : 'Log Specimen'}
                  </button>
                </form>
              </div>
            </div>

            {/* Card 2: Offline-First Queue */}
            <div className={`${styles.card} ${styles.reveal} ${styles.stagger2}`}>
              <div className={styles.cardHeader}>
                <div className={styles.cardIcon}>
                  <svg viewBox="0 0 24 24">
                    <path d="M16.72 11.06A10.94 10.94 0 0 1 19 12.5a9 9 0 0 1-10.3 8.87M1 1l22 22" />
                    <path d="M12.5 6.5a9 9 0 0 1 5.3 1.9M4.3 4.3A9 9 0 0 0 3 12.5a9 9 0 0 0 1.2 4.4" />
                  </svg>
                </div>
                <h3 className={styles.cardTitle}>Offline-First Ledger</h3>
                <p className={styles.cardDesc}>
                  Works even without internet, your data is saved offline and automatically synced once the connection is back.
                </p>
              </div>

              <div className={styles.cardInteractive}>
                <div className={styles.syncStatusSection}>
                  <div className={styles.syncToggle}>
                    <button 
                      onClick={() => setIsOnline(!isOnline)} 
                      className={`${styles.syncToggleBtn} ${isOnline ? styles.syncToggleBtnActive : ''}`}
                    >
                      <span className={`${styles.syncToggleBall} ${isOnline ? styles.syncToggleBallActive : ''}`} />
                    </button>
                    <span className={styles.syncLabel}>Status: {isOnline ? 'Online' : 'Offline'}</span>
                  </div>
                  <span style={{ fontSize: 9, fontWeight: 600, color: isOnline ? 'var(--color-tertiary)' : 'var(--color-error)' }}>
                    {isOnline ? 'Network Active' : 'Disconnected'}
                  </span>
                </div>
                
                <div className={styles.syncList}>
                  {syncQueue.length === 0 ? (
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', fontSize: 10, color: 'var(--color-outline)' }}>
                      All items synced. Queue empty.
                    </div>
                  ) : (
                    syncQueue.map(item => (
                      <div key={item.id} className={styles.syncItem}>
                        <span>{item.id} ({item.type})</span>
                        <span className={`${styles.syncTag} ${item.status === 'Synced' ? styles.tagSynced : styles.tagPending}`}>
                          {item.status}
                        </span>
                      </div>
                    ))
                  )}
                </div>

                <button 
                  onClick={addOfflineSample} 
                  disabled={isOnline} 
                  className={styles.syncBtn}
                  style={{ opacity: isOnline ? 0.5 : 1, cursor: isOnline ? 'not-allowed' : 'pointer' }}
                >
                  Create Offline Entry
                </button>
              </div>
            </div>

            {/* Card 3: Immutable Audit Trails */}
            <div className={`${styles.card} ${styles.reveal} ${styles.stagger3}`}>
              <div className={styles.cardHeader}>
                <div className={styles.cardIcon}>
                  <svg viewBox="0 0 24 24">
                    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                  </svg>
                </div>
                <h3 className={styles.cardTitle}>Immutable Audit Trails</h3>
                <p className={styles.cardDesc}>
                  All actions are permanently recorded, ensuring full traceability and compliance.
                </p>
              </div>

              <div className={styles.cardInteractive}>
                <div className={styles.auditDemo}>
                  <div className={styles.auditHeader}>
                    <span className={styles.auditTitleText}>Sample: DNA-008</span>
                    <span style={{ fontSize: 10, fontWeight: 600 }}>Phase: <span style={{ color: 'var(--color-primary)' }}>{phase}</span></span>
                  </div>
                  
                  <div className={styles.auditLogs}>
                    {auditLogs.map((log, idx) => (
                      <div key={idx} className={styles.auditLogItem}>
                        <span className={styles.auditTime}>{log.time} - {log.action}</span>
                        <span>{log.value}</span>
                      </div>
                    ))}
                  </div>

                  <button onClick={advancePhase} className={styles.auditBtn}>
                    Advance Experiment Phase
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className={styles.footer}>
        <div className={styles.footerInner}>
          <p>&copy; Copyright 2026 LabFlow. All Rights Reserved.</p>
        </div>
      </footer>
    </div>
  );
}
