'use client';
import { useState } from 'react';
import styles from '../landing.module.css';

interface AuditLog {
  action: string;
  value: string;
  time: string;
}

export function FeatureCardAudit() {
  const [phase, setPhase] = useState<'Collection' | 'Extraction' | 'Amplification' | 'Analysis'>('Collection');
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([
    { action: 'CREATE', value: 'Specimen generated by Student A', time: '10:14:02' }
  ]);

  const advancePhase = () => {
    const phases: Array<'Collection' | 'Extraction' | 'Amplification' | 'Analysis'> = [
      'Collection', 'Extraction', 'Amplification', 'Analysis'
    ];
    const currentIndex = phases.indexOf(phase);
    const nextIndex = (currentIndex + 1) % phases.length;
    const nextPhase = phases[nextIndex];
    setPhase(nextPhase);

    const timeStr = new Date().toTimeString().split(' ')[0];
    const newLog: AuditLog = {
      action: 'PHASE_CHANGE',
      value: `Phase updated to ${nextPhase} by Admin`,
      time: timeStr,
    };
    setAuditLogs(prev => [newLog, ...prev]);
  };

  return (
    <div className={`${styles.card} ${styles.reveal} ${styles.stagger3}`}>
      <div className={styles.cardHeader}>
        <div className={styles.cardIcon}>
          <svg viewBox="0 0 24 24">
            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
          </svg>
        </div>
        <h3 className={styles.cardTitle}>Immutable Audit Trails</h3>
        <p className={styles.cardDesc}>
          Every create, update, and phase change is permanently recorded. Export-ready for ethics boards.
        </p>
      </div>
      <div className={styles.cardInteractive}>
        <div className={styles.auditDemo}>
          <div className={styles.auditHeader}>
            <span className={styles.auditTitleText}>Sample: DNA-008</span>
            <span className={styles.auditPhase}>
              Phase: <span className={styles.auditPhaseValue}>{phase}</span>
            </span>
          </div>

          <div className={styles.auditLogs}>
            {auditLogs.map((log, idx) => (
              <div key={idx} className={styles.auditLogItem}>
                <span className={styles.auditTime}>{log.time}</span>
                <span className={styles.auditAction}>{log.action}</span>
                <span className={styles.auditValue}>{log.value}</span>
              </div>
            ))}
          </div>

          <button onClick={advancePhase} className={styles.auditBtn}>
            Advance Experiment Phase
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <line x1="5" y1="12" x2="19" y2="12" />
              <polyline points="12 5 19 12 12 19" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
}
